services:
  db:
    image: mysql:8.0
    container_name: gruponorte-mysql
    restart: always
    environment:
      MYSQL_DATABASE: cadastro_grupo_norte
      MYSQL_ROOT_PASSWORD: root1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot1234"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - gruponorte-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gruponorte-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cadastro_grupo_norte?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Belem
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gruponorte-net

volumes:
  mysql_data:
    driver: local

networks:
  gruponorte-net:
    driver: bridge